AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample

# More info about Globals:
# https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
# More info about Env Vars:
# https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
Globals:
    Function:
        Runtime: python3.6
        MemorySize: 128
        Timeout: 900
        Environment:
            Variables:
                TZ: Asia/Tokyo
        Layers:
            - !Ref Layer

Resources:

    # **************************************************
    # ----- Lambda Functions
    # **************************************************
    FunctionGet:
        # More info about Function Resource:
        # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: Lambda_StepFunctions_Sample_Get
            Handler: Lambda_StepFunctions_Sample_Get.lambda_handler
            CodeUri: 001_Get/
            Description: |
                For Sample
                (Get file from S3 and return its contents as return value)
            Role: !GetAtt RoleForLambda.Arn

    FunctionCal:
        # More info about Function Resource:
        # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: Lambda_StepFunctions_Sample_Cal
            Handler: Lambda_StepFunctions_Sample_Cal.lambda_handler
            CodeUri: 002_Cal/
            Description: |
                For Sample
                (Refers to the event object and squares the numerical data stored in the specified position)
            Role: !GetAtt RoleForLambda.Arn

    # **************************************************
    # ----- Lambda Layer
    # **************************************************
    Layer:
        Type: AWS::Lambda::LayerVersion
        Properties:
            LayerName: LambdaLayer_Lambda_StepFunctions_Sample
            CompatibleRuntimes:
                - python3.6
                - python3.7
            Content:
                S3Bucket: mybucket-deploy
                S3Key: Layer.zip
            Description: Lambda Layer for "Samples-AWS-Serverless-Application"

    # **************************************************
    # ----- IAM
    # **************************************************
    RoleForLambda:
        Type: AWS::IAM::Role
        Properties:
            RoleName: RoleForLambda-Lambda-StepFunctions-Sample
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    -   Action:
                            - "sts:AssumeRole"
                        Effect: "Allow"
                        Principal:
                            Service:
                                - "lambda.amazonaws.com"
    RoleForStepFunctions:
        Type: AWS::IAM::Role
        Properties:
            RoleName: RoleForStepFunctions-Lambda-StepFunctions-Sample
            AssumeRolePolicyDocument:
                Version: 2012-10-17
                Statement:
                    -   Action:
                            - "sts:AssumeRole"
                        Effect: "Allow"
                        Principal:
                            Service:
                                - "events.amazonaws.com"

    PolicyForLambda:
        Type: AWS::IAM::Policy
        Properties:
            PolicyName: PolicyForLambda-Lambda-StepFunctions-Sample
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                    - "Action":
                        - "s3:GetObject"
                        - "s3:PutObject"
                      "Effect": "Allow"
                      "Resource": "*"
            Roles:
                - !Ref RoleForLambda

    PolicyForStepFunctions:
        Type: AWS::IAM::Policy
        Properties:
            PolicyName: PolicyForStepFunctions-Lambda-StepFunctions-Sample
            PolicyDocument:
                Version: 2012-10-17
                Statement:
                    - "Action":
                        - "states:StartExecution"
                      "Effect": "Allow"
                      "Resource": "*"
            Roles:
                - !Ref RoleForStepFunctions

    # **************************************************
    # ----- S3
    # **************************************************
    Bucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub lambda-stepfunctions-sample-${AWS::AccountId}

    # **************************************************
    # ----- Step Functions
    # **************************************************
    StateMachine:
        Type: AWS::StepFunctions::StateMachine
        Properties:
            StateMachineName: Lambda_StepFunctions_Sample_StateMachine
            Fn::Transform:
                Name: AWS::Include
                Parameters:
                    Location:
                        Fn::Sub: s3://mybucket-deploy/statemachine.yaml
            RoleArn: !GetAtt RoleForStepFunctions.Arn

# End
